@startuml

class MathEngine{
    Function function
    double evaluateFunction()
    void addFunction(Function function)
    String printFunction()
    List<String> getVariablesFromFunction()
}
MathEngine --> Function

class Function{
    List<Operation> listOfOperations
    Double evaluate();
    void printEquation();
}

Function --> Operation


interface Expression{
    Double evaluate(Operator)
}

interface Operation{
    int evaluate(Expression expression)
    List<Expression> getExpressions
}

Operation -> Expression

class Sum implements Operation{
    int evaluate(Expression expression)
}

class Variable implements Expression{
}

class Constant implements Expression{
}

interface Expression{}


@enduml